//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Module/Player/PlayerInput/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""_PlayerMapInput"",
            ""id"": ""8a6525dd-02b5-4d46-9fa7-35d82248491a"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""4f506b7b-68c7-4f1f-9210-0e109d75bf21"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rotate"",
                    ""type"": ""Value"",
                    ""id"": ""66dcbaed-b1a6-4810-99a8-c6374700d252"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Value"",
                    ""id"": ""876661b0-3cf9-4540-aa0a-c030a2074d39"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Bomb"",
                    ""type"": ""Button"",
                    ""id"": ""211d5174-1794-4fcc-b5be-3b92e5e77ce6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""c2a187be-db86-4588-be1c-43e65543192c"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c0d807a9-20e3-4939-8fd2-cf07eb17f22a"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""beaf2355-a340-4e9f-b466-fbae70d0d0f7"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""af3d7a54-929e-4515-aee0-c81f02dacf17"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""1531e87d-199e-404e-acca-fecd0bb56bcd"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4d286668-a4cb-41e3-ae44-38b9c4457d5e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""1e9b3e8e-e99a-480d-80bc-842411fde350"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""9b921b84-a742-49ee-9b26-9c23e1c9bace"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8578ffaa-0413-4e28-89a6-a930e54e91b7"",
                    ""path"": ""<Keyboard>/#(V)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8841a2da-fa90-4335-8f7d-f5452654d406"",
                    ""path"": ""<Keyboard>/#(B)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b48b76b-c3d0-4649-b5a2-401896e8c228"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""668e4cd1-b7b7-4375-8435-1912ff3be546"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bomb"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // _PlayerMapInput
        m__PlayerMapInput = asset.FindActionMap("_PlayerMapInput", throwIfNotFound: true);
        m__PlayerMapInput_move = m__PlayerMapInput.FindAction("move", throwIfNotFound: true);
        m__PlayerMapInput_rotate = m__PlayerMapInput.FindAction("rotate", throwIfNotFound: true);
        m__PlayerMapInput_Action = m__PlayerMapInput.FindAction("Action", throwIfNotFound: true);
        m__PlayerMapInput_Bomb = m__PlayerMapInput.FindAction("Bomb", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // _PlayerMapInput
    private readonly InputActionMap m__PlayerMapInput;
    private I_PlayerMapInputActions m__PlayerMapInputActionsCallbackInterface;
    private readonly InputAction m__PlayerMapInput_move;
    private readonly InputAction m__PlayerMapInput_rotate;
    private readonly InputAction m__PlayerMapInput_Action;
    private readonly InputAction m__PlayerMapInput_Bomb;
    public struct _PlayerMapInputActions
    {
        private @PlayerInput m_Wrapper;
        public _PlayerMapInputActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m__PlayerMapInput_move;
        public InputAction @rotate => m_Wrapper.m__PlayerMapInput_rotate;
        public InputAction @Action => m_Wrapper.m__PlayerMapInput_Action;
        public InputAction @Bomb => m_Wrapper.m__PlayerMapInput_Bomb;
        public InputActionMap Get() { return m_Wrapper.m__PlayerMapInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_PlayerMapInputActions set) { return set.Get(); }
        public void SetCallbacks(I_PlayerMapInputActions instance)
        {
            if (m_Wrapper.m__PlayerMapInputActionsCallbackInterface != null)
            {
                @move.started -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnMove;
                @move.performed -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnMove;
                @move.canceled -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnMove;
                @rotate.started -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnRotate;
                @rotate.performed -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnRotate;
                @rotate.canceled -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnRotate;
                @Action.started -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnAction;
                @Bomb.started -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnBomb;
                @Bomb.performed -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnBomb;
                @Bomb.canceled -= m_Wrapper.m__PlayerMapInputActionsCallbackInterface.OnBomb;
            }
            m_Wrapper.m__PlayerMapInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move.started += instance.OnMove;
                @move.performed += instance.OnMove;
                @move.canceled += instance.OnMove;
                @rotate.started += instance.OnRotate;
                @rotate.performed += instance.OnRotate;
                @rotate.canceled += instance.OnRotate;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @Bomb.started += instance.OnBomb;
                @Bomb.performed += instance.OnBomb;
                @Bomb.canceled += instance.OnBomb;
            }
        }
    }
    public _PlayerMapInputActions @_PlayerMapInput => new _PlayerMapInputActions(this);
    public interface I_PlayerMapInputActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnBomb(InputAction.CallbackContext context);
    }
}
